name: Terraform CI

on:
  push:
    branches:
      - main
      - master
  pull_request:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  terraform:
    name: Terraform Plan, Apply & Destroy
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: terraform

    steps:
      # ---------------------------------
      # Checkout
      # ---------------------------------
      - name: Checkout Repository
        uses: actions/checkout@v4

      # ---------------------------------
      # Azure OIDC Login
      # ---------------------------------
      - name: Azure Login via OIDC
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      # ---------------------------------
      # Fetch SSH Key from Key Vault
      # ---------------------------------
      - name: Fetch SSH Key from Key Vault
        run: |
          mkdir -p ~/.ssh
          az keyvault secret show \
            --vault-name kv-rajneesh-prod \
            --name vm-ssh-private-key \
            --query value -o tsv > ~/.ssh/id_rsa

          chmod 600 ~/.ssh/id_rsa

      - name: Generate Public Key
        run: |
          
          az keyvault secret show \
            --vault-name kv-rajneesh-prod \
            --name vm-ssh-key \
            --query value -o tsv > ~/.ssh/id_rsa.pub

          chmod 600 ~/.ssh/id_rsa.pub

      # ---------------------------------
      # Setup Terraform
      # ---------------------------------
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan

      - name: Terraform Apply
        run: terraform apply -auto-approve

      - name: Generate Ansible Inventory
        run: terraform output -raw ansible_inventory > ../ansible_vm_setup/inventory.ini
      # ---------------------------------
      # output variable to generate Ansible inventory file
      # ---------------------------------
      - name: Generate Ansible Inventory
        run: terraform output 

      # ---------------------------------
      # WAIT 10 MINUTES
      # ---------------------------------
      - name: Wait 10 minutes before destroy
        run: sleep 600

      # ---------------------------------
      # Destroy
      # ---------------------------------
      - name: Terraform Destroy
        run: terraform destroy -auto-approve